### ISSUE TITLE
Block errors when opening scap files from the kubectl capture plugin

### ISSUE THREAD

**Issue by byrdog55** [draios/sysdig-inspect#58] opened 2019-07-25 21:10 UTC
capture is created using sysdig version 0.26.1
MacOS client Sysdig Inspect version 0.4.1
version install via brew sysdig 0.24.2_2

In the native MacOS client version 0.4.1 i get
 res = 1 event block length 17835928 greater than read buffer size 65536 
and `csysdig -r capture-1563982162.scap` returns
 Could not initialize reader: invalid block type

**Comment by davideschiera** [comment] 2019-07-25 22:02
Sysdig Inspect v0.4.1 embeds Sysdig v0.26.1, it should definitely be able to read the capture file. Are you able to read the file with the same sysdig installation you used to create the file?


`csysdig` would instead be the one installed with brew, ie. v0.24.2. In this case, the file may not be compatible with the older version. Related to this, there's an open issue to make sure the brew package is updated to the latest version (https://github.com/draios/sysdig/issues/1450). If you need it, you could use the sysdig deployed with Inspect; On my machine:

```
davide-mac sysdig: /Applications/Sysdig\ Inspect-0.4.1.app/Contents/Resources/app/ember-electron/resources/sysdig/sysdig --version
sysdig version 0.26.1
```

**Comment by byrdog55** [comment] 2019-07-25 23:36
the container created by the [kubectl capture plugin](https://github.com/sysdiglabs/kubectl-capture) and does the capture is ephemeral.  Once the capture is complete it copies the file to the directory where the command is run.

On your suggestion I tried the sysdig deployed with inspect: 
`adamantium:kubectl-capture jhayner$ /Applications/Sysdig\ Inspect.app/Contents/Resources/app/ember-electron/resources/sysdig/sysdig --version

sysdig version 0.26.1

adamantium:kubectl-capture jhayner$ file capture-1563982162.scap

capture-1563982162.scap: pcap-ng capture file - version 1.2

adamantium:kubectl-capture jhayner$ /Applications/Sysdig\ Inspect.app/Contents/Resources/app/ember-electron/resources/sysdig/sysdig -r capture-1563982162.scap`

>  res = 1
event block length 17835928 greater than read buffer size 65536

I get the same results on a minimal-install of CentOS 7.6 and running the automatic installation.
```
uname -a
Linux prometheius@adamantium 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

sysdig --version

sysdig version 0.26.1

[jhayner@prometheius@adamantium ~]$ file capture-content-engineering-jenkins-worker-ephemeral-dedicated-07ccv-1564003390.scap

capture-content-engineering-jenkins-worker-ephemeral-dedicated-07ccv-1564003390.scap: pcap-ng capture file - version 1.2
[jhayner@prometheius@adamantium ~]$ sysdig -r capture-content-engineering-jenkins-worker-ephemeral-dedicated-07ccv-1564003390.scap

```
> res = 1
event block length 17835928 greater than read buffer size 65536

**Comment by byrdog55** [comment] 2019-07-25 23:43
Here is the command I ran to create the capture.
`kubectl capture my-pod-name -ns my-namespace --ebpf -M 30 --snaplen 256`

**Comment by davideschiera** [comment] 2019-07-26 00:39
Have you created other captures with `kubectl capture` that you were able to open?

**Comment by byrdog55** [comment] 2019-07-26 01:11
No i’ve created several but never been able to open one. I found this report as well https://github.com/draios/sysdig/issues/867#issuecomment-501245142

I’m wondering if I should create an issue here instead https://github.com/sysdiglabs/kubectl-capture

**Comment by davideschiera** [comment] 2019-07-26 01:20
At this point I'm fairly confident the problem is not on the reader side (sysdig embedded in inspect), but on the writer side. It is possible the kubectl plugin makes the problem more likely (maybe because the download doesn't complete when the pod is deleted).

You're right, I agree it's best to file an issue for https://github.com/sysdiglabs/kubectl-capture, and it would be useful to add reference to both this and https://github.com/draios/sysdig/issues/867.

Thanks!

**Comment by davideschiera** [comment] 2019-07-29 18:20
Closing the issue as the core problem seems to be the one reported in https://github.com/sysdiglabs/kubectl-capture/issues/6 (as well as https://github.com/draios/sysdig/issues/867#issuecomment-498958146).

**Closed by davideschiera** 2019-07-29 18:20 UTC
